### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alexAubin**
## Changes

- Fix ynh_exec_warn_less not being happy with FOO=bar

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
The actual error seems to be about:

```
+ ynh_exec_warn_less yarn build
[...]
yarn run v1.22.15
$ webpack
[webpack-cli] Failed to load '/var/www/thelounge/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'copy-webpack-plugin'
```

**Comment by alexAubin** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
The app now works but installing it from source with npm and Yarn installs the developer version...

Capture d’écran

I made a `.deb` install. It works on my server but the CI fails because of nodejs not being seen as installed: https://ci-apps-dev.yunohost.org/ci/job/4313

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
