### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
So the actual issue with the upgrade from the older commit seems to be : 

```
79034 [37m[1mDEBUG [m[webpack-cli] Failed to load '/var/www/thelounge/webpack.config.js' config
79108 [37m[1mDEBUG [m[webpack-cli] Error: Cannot find module 'vue-loader/lib/plugin'
```

From what I understand, that lib disappeared from the internets maybe ... So I guess we can't install the older version anymore and can legitimately remove it from the test suite

**Pull request merged**
